# Pull the ubi image
FROM registry.redhat.io/ubi7/ubi:7.7-140

### Required Atomic/OpenShift Labels - https://github.com/projectatomic/ContainerApplicationGenericLabels#####
LABEL name="HLS-Service-Broker" \
      vendor="HERE Technologies" \
      version="1.0.4" \
      release="v1.0.4" \
      summary="Open Service Broker for HERE Location Services" \
      description="HLS Service Broker will enable provisioning of HLS Freemium Credentials directly from RedHat platform."

# Install Java runtime
RUN yum update -y &&\
    yum install -y java-1.8.0-openjdk && \
    yum -y autoremove &&\
    yum clean all

# Set the JAVA_HOME variable to make it clear where Java is located
ENV JAVA_HOME /etc/alternatives/jre

# Add VOLUME pointing to /tmp to create working directories for tomcat
VOLUME /tmp

# Point DEPENDENCY to target/dependency where the fat jar is unpacked
ARG DEPENDENCY=target/dependency

# Copy the dependency jars
COPY ${DEPENDENCY}/BOOT-INF/lib /broker/lib

# Copy the META-INF directory
COPY ${DEPENDENCY}/META-INF /broker/META-INF

# Copy the class files of the project
COPY ${DEPENDENCY}/BOOT-INF/classes /broker

# Copy the startup script
COPY script/start-broker.sh /usr/local/bin/start-broker.sh

# Copy the .help.1 makefile
COPY docs/openshift/help.1 /help.1

# Copy the LICENSE file
COPY LICENSE /licenses/LICENSE.txt

# Assign execute permissions to the startup script
RUN chmod +x /usr/local/bin/start-broker.sh

# Start the application
CMD ["start-broker.sh"]
EXPOSE 8080
