# Copyright (C) 2019 HERE Europe B.V.
# Licensed under Apache 2.0, see full license in LICENSE
# SPDX-License-Identifier: Apache-2.0

# Example Service Instance YAML file.

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: devrel-dev-service-instance
  namespace: marketplace
spec:
  clusterServiceClassExternalName: here-service-broker
  clusterServicePlanExternalName: Freemium-XYZ
