# Copyright (C) 2019 HERE Europe B.V.
# Licensed under Apache 2.0, see full license in LICENSE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ b64enc .Values.env.brokerBasicAuthUsername }}
  password: {{ b64enc .Values.env.brokerBasicAuthPassword }}
