# Copyright (C) 2019 HERE Europe B.V.
# Licensed under Apache 2.0, see full license in LICENSE
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  value: {{ default "" .Values.secretKey | b64enc | quote }}
  brokerBasicAuthUsername: {{ .Values.env.brokerBasicAuthUsername | b64enc | quote}}
  brokerBasicAuthPassword: {{ .Values.env.brokerBasicAuthPassword | b64enc | quote}}
  hereClientId: {{ .Values.env.hereClientId }}
  hereAccessKeyId: {{ .Values.env.hereAccessKeyId }}
  hereAccessKeySecret: {{ .Values.env.hereAccessKeySecret }}



